services:
  - type: web
    name: flask-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: IBM_API_KEY
        sync: false
      - key: IBM_PROJECT_ID
        sync: false
      - key: IBM_URL
        value: "https://us-south.ml.cloud.ibm.com"